import assert from "node:assert/strict";
import {createTestHarness} from "wrangler";
import {http,HttpResponse} from "msw";
import {setupServer} from "msw/node";
const ENDPOINT="https://gateway.ai.cloudflare.com/v1/e3aec027af13c557bbcb831d29c1e7b4/test/compat/chat/completions";
const laneModels={"1":"qwen/qwen-reasoner:free","2":"deepseek/deepseek-r1","3":"mistralai/magistral","4":"google/gemini-pro","5":"x-ai/grok-reasoning","6":"moonshotai/kimi-k2","7":"meta-llama/llama-reasoning","8":"nvidia/nemotron-reasoning"};
const routeShard=meta=>{const stage=String(meta?.stage||"").toLowerCase(),capability=String(meta?.capability||"").toLowerCase();if(["planner","judge","meta-judge","governance"].includes(stage))return"plan";if(["coding","quantitative"].includes(capability))return"code";if(["legal","medical","finance"].includes(capability))return"regulated";if(["research","evidence","synthesis"].includes(capability))return"research";if(["risk","strategy","systems","adversarial","forecasting"].includes(capability))return"strategy";if(capability==="creative")return"creative";return"general"};
let calls=[];
const network=setupServer(http.post(ENDPOINT,async({request})=>{const body=await request.json(),meta=JSON.parse(request.headers.get("cf-aig-metadata")||"{}"),keys=Object.keys(meta);assert.equal(keys.length,5);assert.deepEqual(keys.sort(),["capability","cost_mode","depth","lane","stage"].sort());assert.equal(body.model,`dynamic/expert-panel-${routeShard(meta)}-v1`);calls.push({meta,body});let content="analysis ok";if(meta.stage==="planner")content=JSON.stringify({experts:[{role:"产业竞争战略专家",capability:"strategy",mandate:"检验竞争结构与战略选择"},{role:"证据与数据质量审查员",capability:"evidence",mandate:"审查证据强弱与缺口"},{role:"反方投资委员会成员",capability:"adversarial",mandate:"寻找失败情景和反例"}],judges:1,rounds:2,topology:"parallel",cost_mode:"balanced"});else if(meta.stage==="judge")content="final synthesis";else if(String(body.messages?.[1]?.content||"").includes("Other experts' independent analyses"))content="revised analysis";const model=laneModels[String(meta.lane)]||"qwen/qwen-reasoner:free";return HttpResponse.json({model,choices:[{message:{role:"assistant",content}}],usage:{prompt_tokens:10,completion_tokens:10,total_tokens:20}},{headers:{"cf-aig-model":model,"cf-aig-provider":"openrouter"}})}));
network.listen({onUnhandledRequest:"error"});
const server=createTestHarness({workers:[{configPath:"./wrangler.test.jsonc"}]});
async function post(body,headers={}){const r=await server.fetch("https://expert.internal/v1/run",{method:"POST",headers:{"content-type":"application/json",...headers},body:JSON.stringify(body)});return{status:r.status,body:await r.json().catch(()=>null)}}
let code=0;
try{await server.listen();calls=[];const self=await post({task_id:"selftest-dynamic",prompt:"1+1",model_count:2,timeout_seconds:120},{"x-three-center-selftest":"1"});assert.equal(self.status,200);assert.equal(self.body.expert_count,1);assert.equal(self.body.judge_count,1);assert.equal(self.body.models.length,2);assert.equal(self.body.free_models_used.includes("qwen/qwen-reasoner:free"),true);assert.equal(new Set(self.body.companies).size,2);assert.deepEqual(calls.map(x=>x.meta.stage),["expert","judge"]);assert.deepEqual(calls.map(x=>x.body.model),["dynamic/expert-panel-general-v1","dynamic/expert-panel-plan-v1"]);
await server.reset();calls=[];const dynamic=await post({task_id:"dynamic-plan",prompt:"请评估一家复杂平台型公司的竞争战略、证据质量和失败情景，做深度系统分析。",timeout_seconds:240});assert.equal(dynamic.status,200);assert.equal(dynamic.body.panel_plan.planner_source,"cloudflare-panel-architect");assert.equal(dynamic.body.expert_count,3);assert.equal(dynamic.body.judge_count,1);assert.equal(dynamic.body.rounds,2);assert.equal(dynamic.body.topology,"parallel");assert.deepEqual(dynamic.body.experts.map(x=>x.role),["产业竞争战略专家","证据与数据质量审查员","反方投资委员会成员"]);assert.equal(dynamic.body.models.length,4);assert.equal(new Set(dynamic.body.companies).size,4);assert.equal(calls.filter(x=>x.meta.stage==="planner").length,1);assert.equal(calls.filter(x=>x.meta.stage==="expert").length,6);assert.equal(calls.filter(x=>x.meta.stage==="judge").length,1);assert.equal(calls.some(x=>x.meta.cost_mode==="balanced"),true);assert.equal(dynamic.body.free_models_used.length>=1,true);assert.equal(calls[0].body.model,"dynamic/expert-panel-plan-v1");assert.equal(calls.some(x=>x.body.model==="dynamic/expert-panel-research-v1"),true);assert.equal(calls.filter(x=>x.body.model==="dynamic/expert-panel-strategy-v1").length>=4,true);assert.equal(calls[calls.length-1].body.model,"dynamic/expert-panel-plan-v1");console.log(JSON.stringify({ok:true,suite:"dynamic-runtime",selftest_models:self.body.models,dynamic_roles:dynamic.body.experts.map(x=>x.role),calls:calls.length,free_models_allowed:true,company_diverse:true,two_rounds:true,sharded_routes:true}))}catch(e){code=1;console.error(e)}
try{await server.close()}catch{}network.close();process.exit(code);
