import assert from "node:assert/strict";
import { createTestHarness } from "wrangler";
import { http, HttpResponse } from "msw";
import { setupServer } from "msw/node";
const watchdog=setTimeout(()=>process.exit(124),60000);
const within=(p,ms,l)=>Promise.race([p,new Promise((_,rej)=>setTimeout(()=>rej(new Error(`TIMEOUT:${l}`)),ms))]);
const catalog=[{id:"google/gemini-2.5-pro",pricing:{prompt:"0.000001",completion:"0.000001"}},{id:"deepseek/deepseek-r1",pricing:{prompt:"0.000001",completion:"0.000001"}},{id:"mistralai/magistral-medium",pricing:{prompt:"0.000001",completion:"0.000001"}},{id:"qwen/qwen3-235b-a22b",pricing:{prompt:"0.000001",completion:"0.000001"}}];
let chatCalls=0,catalogCalls=0,enter=()=>{},release=()=>{},entered=Promise.resolve(),held=Promise.resolve();
function arm(){entered=new Promise(r=>enter=r);held=new Promise(r=>release=r)}
const network=setupServer(http.get("https://openrouter.ai/api/v1/models",()=>{catalogCalls++;return HttpResponse.json({data:catalog})}),http.post("https://openrouter.ai/api/v1/chat/completions",async({request})=>{chatCalls++;const b=await request.json(),p=(b.messages||[]).map(x=>String(x?.content||"")).join("\n");if(p.includes("HOLD_CHAT")&&chatCalls===1){enter();await held}if(p.includes("BAD_JSON_CHAT"))return HttpResponse.text("{bad-json",{status:200,headers:{"content-type":"application/json"}});return HttpResponse.json({choices:[{message:{content:"Result OK"}}],usage:{prompt_tokens:1,completion_tokens:1,total_tokens:2}})}));
network.listen({onUnhandledRequest:"error"});const server=createTestHarness({workers:[{configPath:"./wrangler.test.jsonc"}]});
async function post(b){const r=await server.fetch("https://expert.internal/v1/run",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(b)});return{status:r.status,body:await r.json().catch(()=>null)}}
const run=(id,p="NORMAL",n=4,t=300)=>post({task_id:id,prompt:p,model_count:n,max_tokens:512,timeout_seconds:t,roles:["A","B","C"]});async function reset(){await server.reset();chatCalls=0;catalogCalls=0;enter=()=>{};release=()=>{};entered=Promise.resolve();held=Promise.resolve()}
let code=0;try{await server.listen();await reset();arm();const h=run("a-holder","HOLD_CHAT",4);await within(entered,5000,"enter");const u=await within(Promise.all(Array.from({length:256},(_,i)=>run(`a-u-${i}`))),25000,"unique");assert.equal(u.filter(x=>x.status===409&&x.body?.error==="BUSY").length,199);assert.equal(u.filter(x=>x.status===429).length,57);assert.equal(chatCalls,1);release();assert.equal((await within(h,10000,"finish")).status,200);assert.equal(chatCalls,4);await reset();const f=await run("a-full","NORMAL",4);assert.equal(f.status,200);assert.equal(f.body.models.length,4);assert.equal(f.body.answers.length,3);assert.equal(chatCalls,4);await reset();const bad=await run("a-bad","BAD_JSON_CHAT",2);assert.equal(bad.status,502);assert.equal(bad.body.error,"UPSTREAM_BAD_JSON");assert.equal(chatCalls,1);console.log(JSON.stringify({ok:true,suite:"expert-extreme-a"}))}catch(e){code=1;console.error(e)}try{await server.close()}catch{}network.close();clearTimeout(watchdog);process.exit(code);