import assert from "node:assert/strict";
import {createHash} from "node:crypto";
const WAVE=Number(process.argv[2]||0);assert.ok(Number.isInteger(WAVE)&&WAVE>=0&&WAVE<4,"INVALID_WAVE_INDEX");
const RAW="https://raw.githubusercontent.com/aistairc/medLLM_QA_benchmark/main/data/en/MedMCQA/medmcqa.jsonl";
const BASE="https://expert-worker.a15280020511.workers.dev/v1/diag/medmcqa-batch-7f2d9a31-20260817";
const SHA="91205dc035b83fd173464aa46e0008302a0b3771",NONCE="b4e8476c8e574c2db71aa49dcf86d291",SAMPLE_N=4000,WAVE_N=1000,BATCH_N=10,CONCURRENCY=5;
const d=await fetch(RAW,{headers:{accept:"text/plain"}});const bytes=Buffer.from(await d.arrayBuffer());assert.equal(d.status,200,`RAW_HTTP_${d.status}`);const gh=createHash("sha1");gh.update(Buffer.from(`blob ${bytes.length}\0`));gh.update(bytes);assert.equal(gh.digest("hex"),SHA,"DATASET_SHA_MISMATCH");
const all=bytes.toString("utf8").split(/\r?\n/).filter(Boolean).map(JSON.parse);assert.ok(all.length>=SAMPLE_N,`DATASET_ROWS_${all.length}`);
const sample=all.map((x,i)=>({x,i,k:createHash("sha256").update(`20260817|${String(x.problem_id||i)}`).digest("hex")})).sort((a,b)=>a.k.localeCompare(b.k)).slice(0,SAMPLE_N).map(v=>v.x);
const waveRows=sample.slice(WAVE*WAVE_N,(WAVE+1)*WAVE_N);assert.equal(waveRows.length,WAVE_N);
const sr=await fetch(`${BASE}/session/start`,{method:"POST",headers:{"x-benchmark-nonce":NONCE,accept:"application/json"}});const s=await sr.json().catch(()=>null);assert.equal(sr.status,200,`SESSION_HTTP_${sr.status}:${JSON.stringify(s)}`);assert.equal(s?.ok,true,JSON.stringify(s));assert.equal(s?.dataset_blob_sha,SHA,JSON.stringify(s));const token=s.token;assert.ok(String(token||"").length>40,"NO_TOKEN");
const waveId=`medmcqa-v3-wave-${WAVE}`,batches=[];for(let o=0;o<WAVE_N;o+=BATCH_N){const part=waveRows.slice(o,o+BATCH_N),batchId=`w${WAVE}-b${String(o/BATCH_N).padStart(3,"0")}`,rows=part.map((x,j)=>({id:String(x.problem_id||`${WAVE}-${o+j}`),question:String(x.problem_text),choices:x.choices.map(String),gold:String(x.answer?.[0]||"").toUpperCase()}));batches.push({batchId,rows})}
async function postJson(path,body,timeoutMs=210000){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeoutMs);try{const r=await fetch(`${BASE}${path}`,{method:"POST",headers:{"content-type":"application/json","x-benchmark-token":token,accept:"application/json"},body:JSON.stringify(body),signal:c.signal});const b=await r.json().catch(()=>null);return{r,b}}catch(e){return{r:null,b:null,error:String(e?.name==="AbortError"?"TIMEOUT":e?.message||e)}}finally{clearTimeout(t)}}
async function runOne(x){const body={dataset_blob_sha:SHA,wave_id:waveId,batch_id:x.batchId,rows:x.rows},res=await postJson("/batch",body);if(res.r?.status===200&&res.b?.ok===true)return res.b;const reason=res.error||`HTTP_${res.r?.status||0}_${res.b?.error||"BATCH_FAILED"}`,f=await postJson("/batch/failure",{dataset_blob_sha:SHA,wave_id:waveId,batch_id:x.batchId,n:x.rows.length,reason},30000);assert.equal(f.r?.status,200,`FAIL_RECORD_HTTP_${f.r?.status||0}:${JSON.stringify(f.b)}`);assert.equal(f.b?.ok,true,JSON.stringify(f.b));return f.b}
const results=[];for(let i=0;i<batches.length;i+=CONCURRENCY){const group=await Promise.all(batches.slice(i,i+CONCURRENCY).map(runOne));results.push(...group)}assert.equal(results.length,100);assert.equal(results.reduce((a,x)=>a+Number(x.n||0),0),WAVE_N);
const ids=batches.map(x=>x.batchId),cr=await postJson("/wave/commit",{wave_id:waveId,batch_ids:ids},60000);assert.equal(cr.r?.status,200,`COMMIT_HTTP_${cr.r?.status||0}:${JSON.stringify(cr.b)}`);assert.equal(cr.b?.ok,true,JSON.stringify(cr.b));assert.equal(cr.b?.n,WAVE_N,JSON.stringify(cr.b));assert.equal(cr.b?.batches,100,JSON.stringify(cr.b));
console.log(JSON.stringify({ok:true,suite:"medmcqa-wave-v3",paid_call:true,wave:WAVE,n:cr.b.n,correct:cr.b.correct,completed:cr.b.completed,parsed:cr.b.parsed,cost:cr.b.cost,whole_batch_failures:cr.b.whole_batch_failures,dataset_rows:all.length,sample_n:SAMPLE_N,concurrency:CONCURRENCY}));
