import app,{CenterGate} from "./guard.js";
import {LANGGRAPH_RUNTIME,probeLangGraphRuntime,runLangGraphRequest} from "./langgraph-runtime.js";
import {dynamicChatEndpoint,dynamicRouteModel,aiGatewayRequestHeaders} from "./ai-gateway.js";
import {guardSemanticProfile} from "./profile-consistency.js";
export {CenterGate};

const ORIGIN="https://expert.internal";
const SERVICE="expert-worker";
const MAX_POSTPROCESS_BYTES=2*1024*1024;
const SOFT_EXECUTION_POLICY=`Execution policy:\n- Prioritize price-performance: prefer the lowest-cost/lower-latency option that is still sufficiently reliable and capable for the task; use a stronger or more expensive model only when it materially improves correctness, robustness, or decision quality. There is no hard spending cap.\n- Control answer length softly: match detail to task complexity, maximize information density, avoid unnecessary repetition, but never truncate material reasoning or omit necessary caveats merely to save tokens or cost. Do not use token limits as a quality or cost-control mechanism.\n- Tools are forbidden. Do not call tools, functions, browsers, web search, external retrieval, code execution, or external actions. Work only from the supplied task/context and model reasoning.\n- Preserve uncertainty, counterarguments, and decision-relevant assumptions when material.`;
const json=(body,status=200)=>Response.json(body,{status,headers:{"cache-control":"no-store"}});
const int=(v,d)=>{const n=Number(v);return Number.isFinite(n)?Math.trunc(n):d};
const clamp=(v,lo,hi,d)=>Math.max(lo,Math.min(hi,int(v,d)));
const PROFILE_ENUMS={task_domain:new Set(["general","legal","finance","coding","quantitative","medical","geospatial","business","policy","science","social","research"]),task_type:new Set(["analysis","coding","quantitative","comparison","planning","synthesis","research"]),complexity:new Set(["standard","high"]),reasoning_depth:new Set(["standard","deep"]),context_size:new Set(["short","medium","long"]),latency_priority:new Set(["normal","fast"])};
const COST_MODES=new Set(["free-first","balanced","quality-first"]);

async function readApp(path,env,ctx){
  const response=await app.fetch(new Request(`${ORIGIN}${path}`,{method:"GET"}),env,ctx);
  const body=await response.json().catch(()=>({ok:false,error:"ADMIN_BAD_JSON"}));
  return {http_status:response.status,body};
}

async function readGate(env){
  if(!env.CENTER_GATE?.get||!env.CENTER_GATE?.idFromName)return {ok:false,error:"CENTER_GATE_UNAVAILABLE",active:null};
  const gate=env.CENTER_GATE.get(env.CENTER_GATE.idFromName("global"));
  const response=await gate.fetch(new Request("https://gate.internal/state",{method:"GET"}));
  const body=await response.json().catch(()=>({ok:false,error:"GATE_BAD_RESPONSE"}));
  return {http_status:response.status,...body};
}

async function adminContext(env,ctx){
  const health=await readApp("/health",env,ctx);
  const source=await readApp("/source",env,ctx);
  const acceptance=await readApp("/v1/acceptance/latest",env,ctx);
  const gate=await readGate(env);
  const version=env.CF_VERSION_METADATA||{};
  const ok=health.http_status===200&&health.body?.ok===true&&source.http_status===200&&source.body?.ok===true&&gate.ok===true;
  return json({ok,service:SERVICE,admin_read_only:true,observed_at:new Date().toISOString(),runtime_version:{id:version.id||null,tag:version.tag||null,timestamp:version.timestamp||null},langgraph:{runtime:LANGGRAPH_RUNTIME,mode:"internal-canary",endpoint:"/v1/langgraph/run",health_endpoint:"/v1/langgraph/health",service_binding_only:true},health:health.body,source:source.body,acceptance:acceptance.body,active_task:gate.active||null,active_state_verified:gate.ok===true,secrets_redacted:true},ok?200:503);
}

function internalOnly(url){return url.hostname==="expert.internal"}
function cleanHeader(v){return String(v||"").trim().replace(/[^0-9A-Za-z@._:/-]/g,"_").slice(0,180)}
function adaptiveConcurrency(input,total,configured){const fast=input?.latency_priority==="fast",deep=input?.reasoning_depth==="deep",high=input?.complexity==="high",long=input?.context_size==="long";let target=fast?Math.min(total,configured):deep||high?Math.min(total,configured,4):Math.min(total,configured,2);if(long&&!fast)target=Math.min(target,3);return Math.max(1,target)}
function requestScopedPanelEnv(input,env){
  const configuredLanes=clamp(env.EXPERT_MAX_LANES,2,8,8),configuredExperts=clamp(env.EXPERT_MAX_EXPERTS,1,8,8),configuredJudges=clamp(env.EXPERT_MAX_JUDGES,0,3,2),configuredInternal=clamp(env.EXPERT_INTERNAL_CONCURRENCY,1,8,6),raw=Number(input?.model_count);
  if(!Number.isFinite(raw)){const expertCeiling=Math.min(configuredExperts,Math.max(1,configuredLanes-1)),internal=adaptiveConcurrency(input,expertCeiling,configuredInternal);return {...env,EXPERT_MAX_EXPERTS:String(expertCeiling),EXPERT_MAX_JUDGES:String(Math.max(1,configuredJudges)),EXPERT_INTERNAL_CONCURRENCY:String(internal)}}
  const total=clamp(raw,1,8,8),judges=Math.min(Math.max(1,configuredJudges),Math.max(0,total-1)),experts=Math.max(1,Math.min(configuredExperts,total-judges)),internal=adaptiveConcurrency(input,experts,configuredInternal);
  return {...env,EXPERT_MAX_LANES:String(Math.min(configuredLanes,Math.max(2,total))),EXPERT_MAX_EXPERTS:String(experts),EXPERT_MAX_JUDGES:String(judges),EXPERT_INTERNAL_CONCURRENCY:String(internal)};
}
function adaptiveTaskSeconds(input){let seconds=240;if(input?.complexity==="high")seconds=420;if(input?.reasoning_depth==="deep")seconds+=60;if(input?.context_size==="medium")seconds+=45;if(input?.context_size==="long")seconds+=120;if(input?.latency_priority==="fast")seconds=Math.round(seconds*0.7);return clamp(seconds,120,600,360)}
function applyAdaptiveRuntimeControls(input){const out={...input};if(!Number.isFinite(Number(out.timeout_seconds)))out.timeout_seconds=adaptiveTaskSeconds(out);out.runtime_control_source="semantic-profile-bounded";return out}

function normalizeExpertInput(input){const normalized={...input};delete normalized.max_tokens;delete normalized.max_output_tokens;delete normalized.token_budget;delete normalized.max_paid_usd;const prompt=String(input?.prompt||"").trim();if(prompt)normalized.prompt=`${prompt}\n\n${SOFT_EXECUTION_POLICY}`;if(!String(normalized.cost_priority||"").trim())normalized.cost_priority="balanced";if(!String(normalized.cost_mode||"").trim())delete normalized.cost_mode;normalized.tools=false;normalized.web=false;return normalized;}
function extractJson(text){const s=String(text||"").trim().replace(/^```(?:json)?\s*/i,"").replace(/\s*```$/i,""),a=s.indexOf("{"),b=s.lastIndexOf("}");if(a<0||b<a)return null;try{return JSON.parse(s.slice(a,b+1))}catch{return null}}
function validProfileValue(key,value){const v=String(value||"").trim().toLowerCase().replace(/[_\s]+/g,"-");return PROFILE_ENUMS[key]?.has(v)?v:null}
function needsSemanticProfile(input){return ["task_domain","task_type","complexity","reasoning_depth","context_size","latency_priority"].some(k=>input?.[k]==null)}
async function semanticProfile(input,env){if(!needsSemanticProfile(input)||!String(input?.prompt||"").trim())return null;const metadata={stage:"planner",lane:"1",capability:"strategy",depth:"standard",cost_mode:"balanced"},controller=new AbortController(),timer=setTimeout(()=>controller.abort(),30000);try{const endpoint=await dynamicChatEndpoint(env),response=await fetch(endpoint,{method:"POST",headers:{"content-type":"application/json",accept:"application/json",...aiGatewayRequestHeaders(env,30000,metadata)},body:JSON.stringify({model:dynamicRouteModel(env,metadata),messages:[{role:"system",content:"Classify the task for expert orchestration only. Do not solve it. Tools and web are forbidden. Return strict JSON only."},{role:"user",content:`Task:\n${String(input.prompt)}\n\nReturn {\"task_domain\": one of general|legal|finance|coding|quantitative|medical|geospatial|business|policy|science|social|research, \"task_domains\": array of all materially relevant domains from the same set, \"task_type\": analysis|coding|quantitative|comparison|planning|synthesis|research, \"complexity\": standard|high, \"reasoning_depth\": standard|deep, \"context_size\": short|medium|long, \"latency_priority\": normal|fast}. Choose the primary task_domain by the capability most central to a correct answer.`}],temperature:0,stream:false}),signal:controller.signal}),body=await response.json().catch(()=>null);if(!response.ok)return null;const raw=extractJson(body?.choices?.[0]?.message?.content),out={};if(!raw)return null;for(const key of Object.keys(PROFILE_ENUMS)){const value=validProfileValue(key,raw?.[key]);if(value)out[key]=value}const domains=Array.isArray(raw?.task_domains)?raw.task_domains.map(x=>validProfileValue("task_domain",x)).filter(Boolean):[];if(domains.length)out.semantic_task_domains=[...new Set(domains)].slice(0,6);return Object.keys(out).length?out:null}catch{return null}finally{clearTimeout(timer)}}
async function applySemanticProfile(original,normalized,env){const inferred=await semanticProfile(original,env);if(!inferred)return normalized;const guarded=guardSemanticProfile(original,inferred),profile=guarded.profile,out={...normalized};for(const key of Object.keys(PROFILE_ENUMS))if(original?.[key]==null&&profile[key]!=null)out[key]=profile[key];if(profile.semantic_task_domains)out.semantic_task_domains=profile.semantic_task_domains;out.profile_source=guarded.guarded?"hybrid-semantic-deterministic-guarded":"ai-gateway-semantic-validated";out.profile_guarded=guarded.guarded;out.profile_guard_conflict_count=guarded.conflicts.length;return out;}

function stripHiddenReasoning(value){let text=String(value??"");for(const tag of ["think","analysis","reasoning"]){text=text.replace(new RegExp(`<${tag}\\b[^>]*>[\\s\\S]*?<\\/${tag}>`,"gi"),"");text=text.replace(new RegExp(`<${tag}\\b[^>]*>[\\s\\S]*$`,"gi"),"");text=text.replace(new RegExp(`<\\/${tag}>`,"gi"),"")}return text.trim()}
function scrubModelOutput(value){if(Array.isArray(value))return value.map(scrubModelOutput);if(value&&typeof value==="object"){const out={};for(const[k,v]of Object.entries(value))out[k]=scrubModelOutput(v);return out}return typeof value==="string"?stripHiddenReasoning(value):value}
function modelCompany(model,provider){const m=String(model||"").toLowerCase(),p=String(provider||"").toLowerCase();if(m.startsWith("@cf/"))return m.split("/")[1]||"";if(m.includes("/"))return m.split("/")[0]||"";return p||""}
async function readJsonBounded(response,maxBytes=MAX_POSTPROCESS_BYTES){const declared=Number(response.headers.get("content-length")||0);if(declared>maxBytes)throw Object.assign(new Error("EXPERT_RESPONSE_TOO_LARGE"),{status:502});if(!response.body)return null;const reader=response.body.getReader(),decoder=new TextDecoder();let bytes=0,text="";while(true){const{done,value}=await reader.read();if(done)break;bytes+=value.byteLength;if(bytes>maxBytes){try{await reader.cancel()}catch{};throw Object.assign(new Error("EXPERT_RESPONSE_TOO_LARGE"),{status:502})}text+=decoder.decode(value,{stream:true})}text+=decoder.decode();try{return text?JSON.parse(text):null}catch{throw Object.assign(new Error("EXPERT_BAD_JSON"),{status:502})}}
function synthesisEvidence(body){const experts=Array.isArray(body?.experts)?body.experts:[],judges=Array.isArray(body?.judges)?body.judges:[],parts=[];for(const x of experts){const content=stripHiddenReasoning(x?.content);if(content)parts.push(`[Expert ${x?.index||parts.length+1}: ${x?.role||"expert"}]\n${content.slice(0,12000)}`)}for(const x of judges){const content=stripHiddenReasoning(x?.content);if(content)parts.push(`[Judge ${x?.index||parts.length+1}: ${x?.role||"judge"}]\n${content.slice(0,12000)}`)}return parts.join("\n\n")}
function finalSynthesisCostMode(body,normalized){const candidate=String(body?.cost_mode||normalized?.cost_mode||"").trim().toLowerCase();if(COST_MODES.has(candidate))return candidate;return body?.task_profile?.reasoning_depth==="deep"?"quality-first":"balanced"}
function finalSynthesisTimeout(body,env){const profile=body?.task_profile||{},maxMs=clamp(env?.EXPERT_MAX_STAGE_MS,15000,180000,120000);let ms=profile.reasoning_depth==="deep"?105000:75000;if(profile.complexity==="high")ms+=15000;if(profile.context_size==="long")ms+=15000;else if(profile.context_size==="medium")ms+=7500;if(profile.latency_priority==="fast")ms=Math.round(ms*0.7);return clamp(ms,30000,maxMs,75000)}
async function gatewayFinalSynthesis(original,normalized,body,env){const evidence=synthesisEvidence(body);if(!evidence)throw Object.assign(new Error("FINAL_SYNTHESIS_EVIDENCE_EMPTY"),{status:502});const used=Math.max(0,int(body?.expert_count,0)+int(body?.judge_count,0)),lane=String(Math.min(8,Math.max(1,used+1))),depth=body?.task_profile?.reasoning_depth==="deep"?"deep":"standard",costMode=finalSynthesisCostMode(body,normalized),metadata={stage:"judge",lane,capability:"synthesis",depth,cost_mode:costMode},timeout=finalSynthesisTimeout(body,env),controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeout);try{const endpoint=await dynamicChatEndpoint(env),response=await fetch(endpoint,{method:"POST",headers:{"content-type":"application/json",accept:"application/json",...aiGatewayRequestHeaders(env,timeout,metadata)},body:JSON.stringify({model:dynamicRouteModel(env,metadata),messages:[{role:"system",content:"You are the final independent adjudicator. Produce only the user-facing final answer. Resolve disagreements by reasoning quality, do not expose chain-of-thought or hidden reasoning, preserve material uncertainty and assumptions, and do not use tools or web."},{role:"user",content:`Original task:\n${String(original?.prompt||normalized?.prompt||"")}\n\nPanel evidence:\n${evidence}\n\nSynthesize the strongest calibrated conclusion. For comparison or decision tasks, give a clear ranking or recommendation and explain the decisive tradeoffs. Do not merely copy the first expert.`}],temperature:0.15,stream:false}),signal:controller.signal}),payload=await response.json().catch(()=>null);if(!response.ok)throw Object.assign(new Error(`FINAL_SYNTHESIS_HTTP_${response.status}`),{status:502});const content=stripHiddenReasoning(payload?.choices?.[0]?.message?.content);if(!content)throw Object.assign(new Error("FINAL_SYNTHESIS_EMPTY"),{status:502});const model=cleanHeader(response.headers.get("cf-aig-model")||payload?.model),provider=cleanHeader(response.headers.get("cf-aig-provider"));return{index:int(body?.judge_count,0)+1,lane:Number(lane),role:"Final synthesis adjudicator",model,provider,company:modelCompany(model,provider),content,free_variant:String(model).toLowerCase().includes(":free"),meta:metadata,timeout_ms:timeout,quality_gate:true}}catch(error){if(error?.name==="AbortError")throw Object.assign(new Error("FINAL_SYNTHESIS_TIMEOUT"),{status:504});throw error}finally{clearTimeout(timer)}}
async function enforceFinalQuality(response,original,normalized,env){const status=response.status,raw=await readJsonBounded(response),body=scrubModelOutput(raw||{});if(!response.ok||body?.ok!==true)return json(body,status);const existing=stripHiddenReasoning(body?.judge?.content||"");if(existing){body.final_answer=existing;body.final_answer_source="panel-final-judge";body.quality_gate={ok:true,mode:"panel-judge",hidden_reasoning_scrubbed:true,expert_one_direct_final:false,runtime_control_source:normalized?.runtime_control_source||null};return json(body,status)}try{const synthesis=await gatewayFinalSynthesis(original,normalized,body,env);body.final_synthesis=synthesis;body.final_answer=synthesis.content;body.final_answer_source="gateway-final-synthesis";body.effective_judge_count=int(body?.judge_count,0)+1;body.quality_gate={ok:true,mode:"mandatory-final-synthesis",hidden_reasoning_scrubbed:true,expert_one_direct_final:false,token_cap:false,tools:false,web:false,runtime_control_source:normalized?.runtime_control_source||null};return json(body,status)}catch(error){return json({ok:false,error:String(error?.message||"FINAL_SYNTHESIS_FAILED"),message:"Expert analyses completed but the mandatory final synthesis quality gate failed",stage:"final-synthesis",expert_execution_ok:true,task_id:body?.task_id||null,task_profile:body?.task_profile||null,expert_count:body?.expert_count||0,panel_judge_count:body?.judge_count||0,quality_gate:{ok:false,mandatory:true,expert_one_direct_final:false,hidden_reasoning_scrubbed:true,runtime_control_source:normalized?.runtime_control_source||null},secrets_redacted:true},error?.status||502)}}

async function routeProbe(req,env){const input=await req.json().catch(()=>null),lane=Math.trunc(Number(input?.lane));if(!Number.isInteger(lane)||lane<1||lane>8)return json({ok:false,error:"INVALID_LANE",secrets_redacted:true},400);const metadata={stage:"route-probe",lane:String(lane),capability:"general",depth:"standard",cost_mode:"balanced"},controller=new AbortController(),timer=setTimeout(()=>controller.abort(),30000);try{const endpoint=await dynamicChatEndpoint(env),response=await fetch(endpoint,{method:"POST",headers:{"content-type":"application/json",accept:"application/json",...aiGatewayRequestHeaders(env,30000,metadata)},body:JSON.stringify({model:dynamicRouteModel(env,metadata),messages:[{role:"user",content:"Return exactly OK. Tools are forbidden."}],temperature:0,stream:false}),signal:controller.signal}),provider=cleanHeader(response.headers.get("cf-aig-provider")),model=cleanHeader(response.headers.get("cf-aig-model")),step=cleanHeader(response.headers.get("cf-aig-step")),ok=response.status===200&&Boolean(provider)&&Boolean(model);return json({ok,probe:"expert-dynamic-route-v2",lane,gateway_http_status:response.status,provider:model?provider:null,model:model||null,gateway_step:step||null,content_scrubbed:true,request_fixed:true,tools_used:false,web_used:false,secrets_redacted:true,error_code:ok?null:`GATEWAY_HTTP_${response.status}`},ok?200:502)}catch(error){return json({ok:false,probe:"expert-dynamic-route-v2",lane,error_code:error?.name==="AbortError"?"GATEWAY_TIMEOUT":"GATEWAY_REQUEST_FAILED",content_scrubbed:true,request_fixed:true,tools_used:false,web_used:false,secrets_redacted:true},502)}finally{clearTimeout(timer)}}

export default{async fetch(req,env,ctx){const url=new URL(req.url);if(req.method==="GET"&&url.pathname==="/v1/admin/context"){if(!internalOnly(url))return json({ok:false,error:"POLICY_DENIED",message:"admin context is service-binding internal only"},403);return adminContext(env,ctx)}if(req.method==="POST"&&url.pathname==="/v1/admin/route-probe"){if(!internalOnly(url))return json({ok:false,error:"POLICY_DENIED",message:"route probe is service-binding internal only"},403);return routeProbe(req,env)}if(req.method==="GET"&&url.pathname==="/v1/langgraph/health"){if(!internalOnly(url))return json({ok:false,error:"POLICY_DENIED",message:"LangGraph runtime is service-binding internal only"},403);const probe=await probeLangGraphRuntime().catch(error=>({ok:false,runtime:LANGGRAPH_RUNTIME,error:String(error?.message||error)}));return json(probe,probe.ok?200:503)}if(req.method==="POST"&&url.pathname==="/v1/langgraph/run"){if(!internalOnly(url))return json({ok:false,error:"POLICY_DENIED",message:"LangGraph runtime is service-binding internal only"},403);const input=await req.json().catch(()=>null);if(!input)return json({ok:false,error:"INVALID_JSON"},400);const result=await runLangGraphRequest(input,env,ctx).catch(error=>({ok:false,runtime:LANGGRAPH_RUNTIME,status:"failed",error:String(error?.message||error)}));return json(result,result.ok?200:result.status==="rejected"?400:502)}if(req.method==="POST"&&url.pathname==="/v1/run"){const input=await req.clone().json().catch(()=>null);if(!input)return app.fetch(req,env,ctx);const profiled=await applySemanticProfile(input,normalizeExpertInput(input),env),normalized=applyAdaptiveRuntimeControls(profiled),scopedEnv=requestScopedPanelEnv(normalized,env),headers=new Headers(req.headers);headers.set("content-type","application/json");headers.delete("content-length");const rewritten=new Request(req,{headers,body:JSON.stringify(normalized)}),response=await app.fetch(rewritten,scopedEnv,ctx);return enforceFinalQuality(response,input,normalized,scopedEnv)}return app.fetch(req,env,ctx)}};
