import { aiGatewayConfigured, aiGatewayRequestHeaders, dynamicChatEndpoint, dynamicRouteModel } from "./ai-gateway.js";
import { readTextBounded } from "./bounded-response.js";

const MAX_BODY_BYTES = 65536;
const MAX_UPSTREAM_BYTES = 1500000;
const DEFAULT_MAX_TOKENS = 4096;
const MAX_MAX_TOKENS = 16384;
const MODEL_TIMEOUT_MS = 30000;
const AUXILIARY_NO_TOOLS_SYSTEM = `AUXILIARY MODEL TOOL ISOLATION:
- You have zero tool authority.
- Never browse or search the web, call APIs, connectors, plugins, functions, or tools, execute code or commands, access repositories/files/external services, or initiate external actions.
- Use only the prompt and evidence already supplied by the controlling system.
- Never emit or request tool_calls/function_call. If external execution or fresh data is required, state that the controlling web GPT must perform it; do not simulate execution.`;

const json = (body, status = 200) => Response.json(body, { status, headers: { "cache-control": "no-store" } });
function redact(value){if(Array.isArray(value))return value.map(redact);if(value&&typeof value==="object"){const out={};for(const[key,item]of Object.entries(value))out[key]=/token|secret|password|authorization|cookie|api.?key/i.test(key)?"[REDACTED]":redact(item);return out}return value}
async function parseBody(request){const declared=Number(request.headers.get("content-length")||0);if(declared>MAX_BODY_BYTES)throw Object.assign(new Error("BODY_TOO_LARGE"),{status:413});const text=await request.text();if(new TextEncoder().encode(text).length>MAX_BODY_BYTES)throw Object.assign(new Error("BODY_TOO_LARGE"),{status:413});if(!text)return{};try{return JSON.parse(text)}catch{throw Object.assign(new Error("INVALID_REQUEST"),{status:400})}}
function rejectToolUse(payload){const message=payload?.choices?.[0]?.message||null,finish=String(payload?.choices?.[0]?.finish_reason||"").toLowerCase(),structured=(Array.isArray(message?.tool_calls)?message.tool_calls.length>0:Boolean(message?.tool_calls))||Boolean(message?.function_call)||/tool_calls?|function_call/.test(finish),content=typeof message?.content==="string"?message.content:"",textual=/<tool_call>|<function_call>|["']tool_calls?["']\s*:\s*\[/i.test(content);if(structured||textual)throw Object.assign(new Error("AUXILIARY_TOOL_USE_FORBIDDEN"),{status:502})}
function contentOf(payload){rejectToolUse(payload);const content=payload?.choices?.[0]?.message?.content;if(typeof content==="string"&&content.trim())return content.trim();if(Array.isArray(content)){const text=content.map(item=>typeof item==="string"?item:item?.text||"").join("\n").trim();if(text)return text}throw Object.assign(new Error("EMPTY_MODEL_OUTPUT"),{status:502})}
async function callRoute(env,messages,maxTokens){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),MODEL_TIMEOUT_MS);try{const response=await fetch(await dynamicChatEndpoint(env),{method:"POST",signal:controller.signal,headers:{"content-type":"application/json",accept:"application/json",...aiGatewayRequestHeaders(env,MODEL_TIMEOUT_MS,{stage:"governance",lane:"1",capability:"strategy",depth:"deep",cost_mode:"quality-first"})},body:JSON.stringify({model:dynamicRouteModel(env),messages,temperature:0.2,stream:false,max_tokens:maxTokens})}),raw=await readTextBounded(response,MAX_UPSTREAM_BYTES);let payload=null;if(raw){try{payload=JSON.parse(raw)}catch{throw Object.assign(new Error("UPSTREAM_BAD_JSON"),{status:502})}}if(!response.ok)throw Object.assign(new Error("UPSTREAM_UNAVAILABLE"),{status:response.status||502,details:redact(payload)});const model=String(response.headers.get("cf-aig-model")||payload?.model||"").trim(),provider=String(response.headers.get("cf-aig-provider")||"").trim();if(!model||!provider)throw Object.assign(new Error("DYNAMIC_ROUTE_METADATA_MISSING"),{status:502});return{payload,model,provider}}catch(error){if(error?.name==="AbortError")throw Object.assign(new Error("UPSTREAM_TIMEOUT"),{status:504});throw error}finally{clearTimeout(timer)}}
export async function runGovernanceRelay(request,env){if(!aiGatewayConfigured(env))return json({ok:false,error:"AI_GATEWAY_NOT_CONFIGURED",message:"Cloudflare AI Gateway token, gateway id, route, or account id is not configured"},503);try{const body=await parseBody(request),prompt=typeof body.prompt==="string"?body.prompt.trim():"";if(!prompt)return json({ok:false,error:"INVALID_REQUEST",message:"prompt required"},400);const maxTokens=Math.max(256,Math.min(MAX_MAX_TOKENS,Number(body.max_tokens||DEFAULT_MAX_TOKENS)||DEFAULT_MAX_TOKENS)),suppliedSystem=typeof body.system==="string"&&body.system.trim()?body.system.trim():"You are the governance copilot for a multi-center decision system. Assist the controlling web GPT with repository governance, code review, fault diagnosis, routing, policy interpretation, maintenance planning, and concise decision support. Do not claim to have executed actions you did not execute. Preserve system constraints and state uncertainty explicitly.",routed=await callRoute(env,[{role:"system",content:`${suppliedSystem}\n\n${AUXILIARY_NO_TOOLS_SYSTEM}`},{role:"user",content:prompt}],maxTokens);return json({ok:true,provider:routed.provider,selection:"cloudflare-adaptive-dynamic-route",route_stage:"governance",model_tier:"quality-first",model:routed.model,content:contentOf(routed.payload),usage:redact(routed.payload?.usage||null),tool_access:"none"})}catch(error){return json({ok:false,error:String(error?.message||"INTERNAL_ERROR"),web_gpt_fallback_required:true,model_tier:"route-policy",tool_access:"none"},error?.status||500)}}
