import {CAPABILITY_ABI_VERSION,expertCapabilityManifest} from "./capability-manifest.js";
import {aiGatewayConfigured,aiGatewayDescriptor,aiGatewayRequestHeaders,openRouterChatEndpoint} from "./ai-gateway.js";
const SERVICE="expert-worker",API_VERSION="2026-08-18.1",MAX_BODY=65536,MAX_UPSTREAM_BYTES=1500000,MAX_MODELS=4,MAX_REPLACEMENTS_PER_STAGE=1;
const POLICY={fail_closed:true,single_active_task:true,network:"openrouter-only",inference_transport:"cloudflare-ai-gateway-openrouter",tools:false,web:false,history_weight:0,reasoning_effort:"high",exclude_providers:["openai","anthropic"],exclude_free:true,exclude_flash:true,max_retries:0,max_model_replacements_per_stage:MAX_REPLACEMENTS_PER_STAGE,max_models:MAX_MODELS,judge_required:true,model_selection:"reasoning+most-popular",exact_company_diversity:true,exact_requested_model_count:true,stage_timeout_bounded:true,total_timeout_bounded:true};
const CAP={task_profiler:true,dynamic_models:true,company_diversity:true,exact_company_diversity:true,model_replacement:true,stage_timeouts:true,total_deadline:true,experts:true,judge:true,openrouter_rest:true,cloudflare_ai_gateway:true,authenticated_gateway:true,inference_cache:false,inference_request_logging:false,fixed_chat_endpoint:true,official_model_catalog:true,tools:false,web:false,duplicate_task_rejected:true,cancel_checked_between_calls:true,external_calls_inside_single_task_lock:true,automatic_retries:false,upstream_response_limit_bytes:MAX_UPSTREAM_BYTES};
const now=()=>new Date().toISOString(),rid=()=>crypto.randomUUID();
const int=(v,d)=>{const n=Number(v);return Number.isFinite(n)?Math.trunc(n):d};
const clamp=(v,lo,hi,d)=>Math.max(lo,Math.min(hi,int(v,d)));
const json=(x,s=200)=>Response.json(x,{status:s,headers:{"cache-control":"no-store"}});
const err=(c,m,s=400,d)=>json({ok:false,error:c,message:m,...(d?{details:redact(d)}:{})},s);
function redact(v){if(Array.isArray(v))return v.map(redact);if(v&&typeof v==="object"){const o={};for(const[k,x]of Object.entries(v))o[k]=/token|secret|password|authorization|cookie|api.?key/i.test(k)?"[REDACTED]":redact(x);return o}return v}
async function parse(req){const n=Number(req.headers.get("content-length")||0);if(n>MAX_BODY)throw Object.assign(new Error("BODY_TOO_LARGE"),{status:413});const t=await req.text();if(new TextEncoder().encode(t).length>MAX_BODY)throw Object.assign(new Error("BODY_TOO_LARGE"),{status:413});if(!t)return{};try{return JSON.parse(t)}catch{throw Object.assign(new Error("INVALID_REQUEST"),{status:400})}}
async function digest(){const h=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(JSON.stringify({SERVICE,API_VERSION,POLICY,CAP})));return[...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,"0")).join("")}
function gate(env){return env.CENTER_GATE.get(env.CENTER_GATE.idFromName("global"))}
async function gs(env,p,m="GET",b){const i={method:m,headers:{"content-type":"application/json"}};if(b!==undefined)i.body=JSON.stringify(b);const r=await gate(env).fetch(new Request(`https://gate.internal${p}`,i));return{http:r.status,...await r.json().catch(()=>({ok:false,error:"GATE_BAD_RESPONSE"}))}}
const acquire=(env,id,ttl)=>gs(env,"/acquire","POST",{task_id:id,kind:"expert",lease_seconds:ttl});
const release=(env,id)=>gs(env,"/release","POST",{task_id:id});
const save=(env,id,p)=>gs(env,`/task/${encodeURIComponent(id)}`,"POST",p);
const load=(env,id)=>gs(env,`/task/${encodeURIComponent(id)}`);
export class CenterGate{
  constructor(state){this.state=state}
  async fetch(req){const u=new URL(req.url),s=this.state.storage,j=async()=>{try{return await req.json()}catch{return{}}};const active=async()=>{const a=await s.get("active");if(a&&a.expires<=Date.now()){await s.delete("active");return null}return a||null};
    if(req.method==="GET"&&u.pathname==="/state")return json({ok:true,active:await active()});
    if(req.method==="POST"&&u.pathname==="/acquire"){const b=await j(),a=await active();if(a)return json({ok:false,error:"BUSY",active:a},409);const id=String(b.task_id||"");if(!id)return json({ok:false,error:"INVALID_REQUEST"},400);const rec={task_id:id,acquired_at:now(),expires:Date.now()+Math.max(30,Math.min(900,int(b.lease_seconds,300)))*1000};await s.put("active",rec);return json({ok:true,active:rec})}
    if(req.method==="POST"&&u.pathname==="/release"){const b=await j(),a=await active();if(!a)return json({ok:true,released:false});if(a.task_id!==b.task_id)return json({ok:false,error:"LOCK_OWNER_MISMATCH",active:a},409);await s.delete("active");return json({ok:true,released:true})}
    if(req.method==="POST"&&u.pathname==="/rate"){const b=await j(),lim=Math.max(1,Math.min(200,int(b.limit,20))),m=Math.floor(Date.now()/60000),k=`rate:${m}`,c=(await s.get(k)||0)+1;await s.put(k,c);await s.delete(`rate:${m-2}`);return c<=lim?json({ok:true,count:c,limit:lim}):json({ok:false,error:"RATE_LIMITED",count:c,limit:lim},429)}
    let m=u.pathname.match(/^\/task\/([^/]+)$/);if(m&&req.method==="GET")return json({ok:true,task:await s.get(`task:${decodeURIComponent(m[1])}`)||null});if(m&&req.method==="POST"){const id=decodeURIComponent(m[1]),old=await s.get(`task:${id}`)||{},rec={...old,...redact(await j()),task_id:id};await s.put(`task:${id}`,rec);return json({ok:true,task:rec})}
    m=u.pathname.match(/^\/task\/([^/]+)\/cancel$/);if(m&&req.method==="POST"){const id=decodeURIComponent(m[1]),k=`task:${id}`,old=await s.get(k);if(!old)return json({ok:false,error:"TASK_NOT_FOUND"},404);const rec={...old,cancel_requested:true,cancel_requested_at:now()};await s.put(k,rec);return json({ok:true,task:rec})}
    return json({ok:false,error:"NOT_FOUND"},404)
  }
}
function allowed(id){const x=String(id||"").toLowerCase();return x&&!x.startsWith("openai/")&&!x.startsWith("anthropic/")&&!x.includes("claude")&&!x.includes("flash")&&!x.includes(":free")}
function nonFree(m){const p=m?.pricing||{};return Number(p.prompt||0)>0||Number(p.completion||0)>0||Number(p.request||0)>0}
function company(id){return String(id).split("/")[0].toLowerCase()}
function remaining(deadline){return Math.max(0,deadline-Date.now())}
async function fetchJsonBounded(url,init,ms=60000){const c=new AbortController(),t=setTimeout(()=>c.abort(),Math.max(1,ms));try{const r=await fetch(url,{...init,signal:c.signal}),raw=await r.text();if(new TextEncoder().encode(raw).length>MAX_UPSTREAM_BYTES)throw Object.assign(new Error("UPSTREAM_RESPONSE_TOO_LARGE"),{status:502});let x=null;if(raw){try{x=JSON.parse(raw)}catch{throw Object.assign(new Error("UPSTREAM_BAD_JSON"),{status:502})}}if(!r.ok)throw Object.assign(new Error("UPSTREAM_UNAVAILABLE"),{status:r.status||502,details:redact(x)});return x}catch(e){if(e?.name==="AbortError")throw Object.assign(new Error("UPSTREAM_TIMEOUT"),{status:504});throw e}finally{clearTimeout(t)}}
async function modelCatalog(env,deadline){const u=new URL("https://openrouter.ai/api/v1/models");u.searchParams.set("supported_parameters","reasoning");u.searchParams.set("sort","most-popular");u.searchParams.set("output_modalities","text");const ms=Math.min(8000,remaining(deadline));if(ms<=0)throw Object.assign(new Error("TASK_DEADLINE_EXCEEDED"),{status:504});const x=await fetchJsonBounded(u,{headers:{authorization:`Bearer ${env.OPENROUTER_API_KEY}`,accept:"application/json"}},ms);return(x?.data||[]).filter(m=>allowed(m?.id)&&nonFree(m))}
async function selectModelPlan(env,count,requested,deadline){const list=await modelCatalog(env,deadline),byId=new Map(list.map(m=>[m.id,m])),primary=[],primaryCompanies=new Set();for(const id of Array.isArray(requested)?requested:[]){const m=byId.get(String(id));if(!m)continue;const co=company(m.id);if(primaryCompanies.has(co))continue;primaryCompanies.add(co);primary.push(m.id);if(primary.length>=count)break}for(const m of list){if(primary.length>=count)break;const co=company(m.id);if(primaryCompanies.has(co))continue;primaryCompanies.add(co);primary.push(m.id)}if(primary.length!==count)throw Object.assign(new Error("NOT_ENOUGH_UNIQUE_MODEL_COMPANIES"),{status:502,details:{requested_count:count,eligible_unique_companies:primary.length}});const reserves=[],reserveCompanies=new Set();for(const m of list){const co=company(m.id);if(primaryCompanies.has(co)||reserveCompanies.has(co))continue;reserveCompanies.add(co);reserves.push(m.id);if(reserves.length>=8)break}return{primary,reserves}}
async function call(env,model,messages,maxTokens,ms){const endpoint=await openRouterChatEndpoint(env);return fetchJsonBounded(endpoint,{method:"POST",headers:{authorization:`Bearer ${env.OPENROUTER_API_KEY}`,"content-type":"application/json",accept:"application/json",...aiGatewayRequestHeaders(env,ms)},body:JSON.stringify({model,messages,reasoning:{effort:"high"},temperature:0.2,stream:false,...(maxTokens?{max_tokens:maxTokens}:{})})},ms)}
async function ensureNotCancelled(env,id){const t=await load(env,id);if(t.task?.cancel_requested)throw Object.assign(new Error("CANCELLED"),{status:409})}
function retryableReplacement(e){return["UPSTREAM_TIMEOUT","EMPTY_MODEL_OUTPUT"].includes(String(e?.message||""))}
function takeReserve(reserves,usedCompanies){while(reserves.length){const m=reserves.shift();if(!usedCompanies.has(company(m)))return m}return null}
function contentOf(out){const c=String(out?.choices?.[0]?.message?.content||"").trim();if(!c)throw Object.assign(new Error("EMPTY_MODEL_OUTPUT"),{status:502});return c}
async function stage({env,id,stageName,role,userPrompt,systemPrompt,primary,reserves,usedCompanies,maxTokens,stageTimeoutMs,deadline}){const attempts=[];let model=primary;for(let attempt=0;attempt<=MAX_REPLACEMENTS_PER_STAGE;attempt++){await ensureNotCancelled(env,id);const left=remaining(deadline);if(left<=0)throw Object.assign(new Error("TASK_DEADLINE_EXCEEDED"),{status:504,details:{stage:stageName,attempts}});if(attempt>0){model=takeReserve(reserves,usedCompanies);if(!model)throw Object.assign(new Error("NO_REPLACEMENT_MODEL_AVAILABLE"),{status:502,details:{stage:stageName,attempts}})}const started=Date.now(),timeoutMs=Math.max(1,Math.min(stageTimeoutMs,left));await save(env,id,{status:"running",current_stage:stageName,current_model:model,current_model_company:company(model),current_attempt:attempt+1,stage_started_at:now()});try{const out=await call(env,model,[{role:"system",content:systemPrompt},{role:"user",content:userPrompt}],maxTokens,timeoutMs),content=contentOf(out),elapsed_ms=Date.now()-started;usedCompanies.add(company(model));attempts.push({model,company:company(model),attempt:attempt+1,status:"completed",elapsed_ms});return{model,content,usage:redact(out?.usage||null),attempts}}catch(e){const elapsed_ms=Date.now()-started;attempts.push({model,company:company(model),attempt:attempt+1,status:"failed",error:String(e?.message||e),elapsed_ms});await save(env,id,{last_stage_error:String(e?.message||e),last_failed_model:model,last_failed_company:company(model),last_failed_stage:stageName,last_failed_elapsed_ms:elapsed_ms});if(attempt>=MAX_REPLACEMENTS_PER_STAGE||!retryableReplacement(e)||remaining(deadline)<=0)throw Object.assign(e,{details:{...(e?.details||{}),stage:stageName,attempts}})}}throw Object.assign(new Error("STAGE_FAILED"),{status:502,details:{stage:stageName,attempts}})}
async function run(req,env){
  if(!env.OPENROUTER_API_KEY)return err("UPSTREAM_AUTH_FAILED","OPENROUTER_API_KEY is not configured",503);
  if(!aiGatewayConfigured(env))return err("AI_GATEWAY_NOT_CONFIGURED","Cloudflare AI Gateway binding or gateway id is not configured",503);
  const rate=await gs(env,"/rate","POST",{limit:int(env.RATE_LIMIT_PER_MIN,20)});if(!rate.ok)return err("RATE_LIMITED","Expert budget exceeded",429);
  const b=await parse(req);if(!b.prompt||typeof b.prompt!=="string")return err("INVALID_REQUEST","prompt required",400);
  const id=String(b.task_id||b.request_id||rid()),previous=await load(env,id);if(previous.task)return err("DUPLICATE_TASK","task_id already exists; duplicate expert execution blocked",409,{task_id:id,status:previous.task.status});
  const count=Math.max(2,Math.min(MAX_MODELS,int(b.model_count,4))),totalSeconds=clamp(b.timeout_seconds,10,300,240),expertStageSeconds=clamp(b.model_timeout_seconds,1,60,45),judgeStageSeconds=clamp(b.judge_timeout_seconds,1,75,60),deadline=Date.now()+totalSeconds*1000,lock=await acquire(env,id,Math.min(900,Math.max(300,totalSeconds+30)));if(!lock.ok)return err("BUSY","Another expert task is active",409,lock.active);
  await save(env,id,{status:"selecting",created_at:now(),requested_model_count:count,total_timeout_seconds:totalSeconds,expert_stage_timeout_seconds:expertStageSeconds,judge_stage_timeout_seconds:judgeStageSeconds,max_model_replacements_per_stage:MAX_REPLACEMENTS_PER_STAGE});
  try{
    await ensureNotCancelled(env,id);const plan=await selectModelPlan(env,count,b.models,deadline),expertPrimaries=plan.primary.slice(0,-1),judgePrimary=plan.primary.at(-1),reserves=[...plan.reserves],usedCompanies=new Set(),answers=[],receipt=[];await save(env,id,{status:"running",planned_models:plan.primary,reserve_models:plan.reserves,planned_company_count:new Set(plan.primary.map(company)).size});
    for(let i=0;i<expertPrimaries.length;i++){const role=Array.isArray(b.roles)&&b.roles[i]?String(b.roles[i]).slice(0,120):`Expert ${i+1}`,r=await stage({env,id,stageName:`expert-${i+1}`,role,userPrompt:b.prompt,systemPrompt:`You are ${role}. Analyze independently. Do not use tools or web. State uncertainty and unsupported assumptions.`,primary:expertPrimaries[i],reserves,usedCompanies,maxTokens:int(b.max_tokens,0)||undefined,stageTimeoutMs:expertStageSeconds*1000,deadline});answers.push({model:r.model,role,content:r.content,usage:r.usage});receipt.push({stage:`expert-${i+1}`,role,selected_model:expertPrimaries[i],final_model:r.model,replaced:r.model!==expertPrimaries[i],attempts:r.attempts})}
    await ensureNotCancelled(env,id);if(remaining(deadline)<=0)throw Object.assign(new Error("TASK_DEADLINE_EXCEEDED"),{status:504});const synthesis=`Question:\n${b.prompt}\n\nIndependent expert answers:\n${answers.map((a,i)=>`[${i+1}] ${a.model} (${a.role})\n${a.content}`).join("\n\n")}`,jr=await stage({env,id,stageName:"judge",role:"Final judge",userPrompt:synthesis,systemPrompt:"You are the final judge. Compare the independent analyses, resolve conflicts, reject unsupported claims, and return the best calibrated synthesis. Do not use tools or web.",primary:judgePrimary,reserves,usedCompanies,maxTokens:int(b.max_tokens,0)||undefined,stageTimeoutMs:judgeStageSeconds*1000,deadline});receipt.push({stage:"judge",role:"Final judge",selected_model:judgePrimary,final_model:jr.model,replaced:jr.model!==judgePrimary,attempts:jr.attempts});const models=[...answers.map(a=>a.model),jr.model],uniqueCompanies=new Set(models.map(company)).size;if(models.length!==count||uniqueCompanies!==count)throw Object.assign(new Error("COMPANY_DIVERSITY_INVARIANT_FAILED"),{status:502,details:{models,unique_companies:uniqueCompanies,required:count}});const rec={status:"completed",models,answers,judge:{model:jr.model,content:jr.content,usage:jr.usage},execution_receipt:receipt,company_diverse:true,finished_at:now(),elapsed_ms:Math.max(0,totalSeconds*1000-remaining(deadline))};await save(env,id,rec);return json({ok:true,task_id:id,...rec});
  }catch(e){if(e?.message==="CANCELLED"){await save(env,id,{status:"cancelled",finished_at:now()});return err("CANCELLED","Expert task cancelled",409,{task_id:id})}await save(env,id,{status:"failed",error:String(e?.message||"UPSTREAM_UNAVAILABLE"),message:String(e?.message||e),details:redact(e?.details),finished_at:now()});return err(e?.message||"UPSTREAM_UNAVAILABLE","OpenRouter expert execution failed",e?.status||502,{task_id:id,...(e?.details?{stage_details:redact(e.details)}:{})})}finally{await release(env,id)}
}
async function handle(req,env){const u=new URL(req.url);if(req.method==="GET"&&u.pathname==="/health")return json({ok:true,status:"ready",service:SERVICE,api_version:API_VERSION,openrouter:{configured:Boolean(env.OPENROUTER_API_KEY)&&aiGatewayConfigured(env),...aiGatewayDescriptor(env)}});if(req.method==="GET"&&(u.pathname==="/v1/policy"||u.pathname==="/policy"))return json({ok:true,service:SERVICE,policy:POLICY});if(req.method==="GET"&&(u.pathname==="/v1/capabilities"||u.pathname==="/capabilities"))return json({ok:true,service:SERVICE,capabilities:CAP,capability_abi_version:CAPABILITY_ABI_VERSION,capability_manifest:expertCapabilityManifest({configured:Boolean(env.OPENROUTER_API_KEY)&&aiGatewayConfigured(env)})});if(req.method==="GET"&&(u.pathname==="/quota"||u.pathname==="/v1/quota"))return json({ok:true,rate_limit_per_min:int(env.RATE_LIMIT_PER_MIN,20),single_active_task:true,max_models:MAX_MODELS,max_retries:0,max_model_replacements_per_stage:MAX_REPLACEMENTS_PER_STAGE,default_total_timeout_seconds:240,default_expert_stage_timeout_seconds:45,default_judge_stage_timeout_seconds:60});if(req.method==="GET"&&u.pathname==="/source")return json({ok:true,service:SERVICE,api_version:API_VERSION,source_digest:await digest(),secrets_redacted:true});if(req.method==="GET"&&u.pathname==="/v1/acceptance/latest")return json({ok:true,service:SERVICE,status:"not_verified",run_id:null,receipt_digest:null});if(req.method==="GET"&&u.pathname==="/openapi.json")return json({openapi:"3.1.0",info:{title:"Expert Center",version:API_VERSION},paths:{"/health":{get:{}},"/v1/policy":{get:{}},"/v1/capabilities":{get:{}},"/v1/run":{post:{}},"/v1/status":{post:{}},"/v1/cancel":{post:{}}}});if(req.method==="POST"&&u.pathname==="/v1/status"){const b=await parse(req);if(!b.task_id)return err("INVALID_REQUEST","task_id required",400);const x=await load(env,b.task_id);return x.task?json({ok:true,task:x.task}):err("INVALID_REQUEST","Task not found",404)}if(req.method==="POST"&&u.pathname==="/v1/cancel"){const b=await parse(req);if(!b.task_id)return err("INVALID_REQUEST","task_id required",400);const x=await gs(env,`/task/${encodeURIComponent(b.task_id)}/cancel`,"POST",{});return json({ok:x.ok,task:x.task||null,cancellation_pending:true,lock_retained:true},202)}if(req.method==="POST"&&u.pathname==="/v1/run")return run(req,env);return err("INVALID_REQUEST","Route not found",404)}
export default{async fetch(req,env){try{return await handle(req,env)}catch(e){return err(e?.message||"INTERNAL_ERROR","Request failed",e?.status||500,e?.details)}}};
