import {CAPABILITY_ABI_VERSION,expertCapabilityManifest} from "./capability-manifest.js";
import {aiGatewayConfigured,aiGatewayDescriptor,aiGatewayRequestHeaders,dynamicChatEndpoint,dynamicRouteModel} from "./ai-gateway.js";
import {readTextBounded} from "./bounded-response.js";
import {profileExpertTask} from "./task-profile.js";

const SERVICE="expert-worker",API_VERSION="2026-08-18.3",MAX_BODY=65536,MAX_UPSTREAM_BYTES=1500000,MAX_MODELS=4;
const POLICY={fail_closed:true,single_active_task:true,network:"cloudflare-ai-gateway-only",inference_transport:"cloudflare-ai-gateway-dynamic-route",tools:false,web:false,history_weight:0,reasoning_effort:"high",exclude_providers:["openai","anthropic"],exclude_free:true,exclude_flash:true,worker_retries:0,cloudflare_model_fallback:true,max_models:MAX_MODELS,judge_required:true,model_selection:"cloudflare-dynamic-route",candidate_pool_source:"openrouter-intelligence-ranking",candidate_pool_runtime_fetch:false,task_profile_metadata:true,exact_company_diversity:true,exact_requested_model_count:true,stage_timeout_bounded:true,total_timeout_bounded:true};
const CAP={task_profiler:true,dynamic_models:true,company_diversity:true,exact_company_diversity:true,cloudflare_model_fallback:true,stage_timeouts:true,total_deadline:true,experts:true,judge:true,openrouter_rest:false,cloudflare_ai_gateway:true,authenticated_gateway:true,inference_cache:"gateway-default",inference_request_logging:"gateway-default",dynamic_route:true,dynamic_route_metadata:true,task_profile_metadata:true,tools:false,web:false,duplicate_task_rejected:true,cancel_checked_between_calls:true,external_calls_inside_single_task_lock:true,automatic_worker_retries:false,upstream_response_limit_bytes:MAX_UPSTREAM_BYTES,task_persistence:"operational-metadata-only",durable_model_content:false};
const now=()=>new Date().toISOString(),rid=()=>crypto.randomUUID();
const int=(v,d)=>{const n=Number(v);return Number.isFinite(n)?Math.trunc(n):d};
const clamp=(v,lo,hi,d)=>Math.max(lo,Math.min(hi,int(v,d)));
const json=(x,s=200)=>Response.json(x,{status:s,headers:{"cache-control":"no-store"}});
const err=(c,m,s=400,d)=>json({ok:false,error:c,message:m,...(d?{details:redact(d)}:{})},s);
function redact(v){if(Array.isArray(v))return v.map(redact);if(v&&typeof v==="object"){const o={};for(const[k,x]of Object.entries(v))o[k]=/token|secret|password|authorization|cookie|api.?key/i.test(k)?"[REDACTED]":redact(x);return o}return v}
async function parse(req){const n=Number(req.headers.get("content-length")||0);if(n>MAX_BODY)throw Object.assign(new Error("BODY_TOO_LARGE"),{status:413});const t=await req.text();if(new TextEncoder().encode(t).length>MAX_BODY)throw Object.assign(new Error("BODY_TOO_LARGE"),{status:413});if(!t)return{};try{return JSON.parse(t)}catch{throw Object.assign(new Error("INVALID_REQUEST"),{status:400})}}
async function digest(){const h=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(JSON.stringify({SERVICE,API_VERSION,POLICY,CAP})));return[...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function outputDigest(value){const h=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(JSON.stringify(value)));return[...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,"0")).join("")}
function gate(env,shard="global"){return env.CENTER_GATE.get(env.CENTER_GATE.idFromName(shard))}
async function gs(env,p,m="GET",b,shard="global"){const i={method:m,headers:{"content-type":"application/json"}};if(b!==undefined)i.body=JSON.stringify(b);const r=await gate(env,shard).fetch(new Request(`https://gate.internal${p}`,i));return{http:r.status,...await r.json().catch(()=>({ok:false,error:"GATE_BAD_RESPONSE"}))}}
const acquire=(env,id,ttl)=>gs(env,"/acquire","POST",{task_id:id,kind:"expert",lease_seconds:ttl});
const release=(env,id)=>gs(env,"/release","POST",{task_id:id});
const save=(env,id,p)=>gs(env,`/task/${encodeURIComponent(id)}`,"POST",p,`task:${id}`);
const load=(env,id)=>gs(env,`/task/${encodeURIComponent(id)}`,"GET",undefined,`task:${id}`);

export class CenterGate{
  constructor(state){this.state=state}
  async fetch(req){const u=new URL(req.url),s=this.state.storage,j=async()=>{try{return await req.json()}catch{return{}}};const active=async()=>{const a=await s.get("active");if(a&&a.expires<=Date.now()){await s.delete("active");return null}return a||null};
    if(req.method==="GET"&&u.pathname==="/state")return json({ok:true,active:await active()});
    if(req.method==="POST"&&u.pathname==="/acquire"){const b=await j(),a=await active();if(a)return json({ok:false,error:"BUSY",active:a},409);const id=String(b.task_id||"");if(!id)return json({ok:false,error:"INVALID_REQUEST"},400);const rec={task_id:id,acquired_at:now(),expires:Date.now()+Math.max(30,Math.min(900,int(b.lease_seconds,300)))*1000};await s.put("active",rec);return json({ok:true,active:rec})}
    if(req.method==="POST"&&u.pathname==="/release"){const b=await j(),a=await active();if(!a)return json({ok:true,released:false});if(a.task_id!==b.task_id)return json({ok:false,error:"LOCK_OWNER_MISMATCH",active:a},409);await s.delete("active");return json({ok:true,released:true})}
    if(req.method==="POST"&&u.pathname==="/rate"){const b=await j(),lim=Math.max(1,Math.min(200,int(b.limit,20))),m=Math.floor(Date.now()/60000),k=`rate:${m}`,c=(await s.get(k)||0)+1;await s.put(k,c);await s.delete(`rate:${m-2}`);return c<=lim?json({ok:true,count:c,limit:lim}):json({ok:false,error:"RATE_LIMITED",count:c,limit:lim},429)}
    let m=u.pathname.match(/^\/task\/([^/]+)$/);if(m&&req.method==="GET")return json({ok:true,task:await s.get(`task:${decodeURIComponent(m[1])}`)||null});if(m&&req.method==="POST"){const id=decodeURIComponent(m[1]),old=await s.get(`task:${id}`)||{},rec={...old,...redact(await j()),task_id:id};await s.put(`task:${id}`,rec);return json({ok:true,task:rec})}
    m=u.pathname.match(/^\/task\/([^/]+)\/cancel$/);if(m&&req.method==="POST"){const id=decodeURIComponent(m[1]),k=`task:${id}`,old=await s.get(k);if(!old)return json({ok:false,error:"TASK_NOT_FOUND"},404);const rec={...old,cancel_requested:true,cancel_requested_at:now()};await s.put(k,rec);return json({ok:true,task:rec})}
    return json({ok:false,error:"NOT_FOUND"},404)
  }
}

function remaining(deadline){return Math.max(0,deadline-Date.now())}
function company(model,provider){const m=String(model||"").toLowerCase(),p=String(provider||"").toLowerCase();if(m.startsWith("@cf/"))return m.split("/")[1]||"";if(m.includes("/"))return m.split("/")[0];if(p&&!['dynamic','compat','openrouter','workers-ai'].includes(p))return p;return""}
function allowedRouteSelection(model,provider){const joined=`${provider||""}/${model||""}`.toLowerCase();return Boolean(model)&&!joined.includes("openai")&&!joined.includes("anthropic")&&!joined.includes("claude")&&!joined.includes("flash")&&!joined.includes(":free")}
async function fetchGatewayBounded(url,init,ms=60000){const c=new AbortController(),t=setTimeout(()=>c.abort(),Math.max(1,ms));try{const r=await fetch(url,{...init,signal:c.signal}),raw=await readTextBounded(r,MAX_UPSTREAM_BYTES);let payload=null;if(raw){try{payload=JSON.parse(raw)}catch{throw Object.assign(new Error("UPSTREAM_BAD_JSON"),{status:502})}}if(!r.ok)throw Object.assign(new Error("UPSTREAM_UNAVAILABLE"),{status:r.status||502,details:redact(payload)});const model=String(r.headers.get("cf-aig-model")||payload?.model||"").trim(),provider=String(r.headers.get("cf-aig-provider")||"").trim();if(!model||!provider)throw Object.assign(new Error("DYNAMIC_ROUTE_METADATA_MISSING"),{status:502});return{payload,route:{model,provider}}}catch(e){if(e?.name==="AbortError")throw Object.assign(new Error("UPSTREAM_TIMEOUT"),{status:504});throw e}finally{clearTimeout(t)}}
async function ensureNotCancelled(env,id){const t=await load(env,id);if(t.task?.cancel_requested)throw Object.assign(new Error("CANCELLED"),{status:409})}
function contentOf(out){const c=out?.choices?.[0]?.message?.content;if(typeof c==="string"&&c.trim())return c.trim();if(Array.isArray(c)){const text=c.map(x=>typeof x==="string"?x:x?.text||"").join("\n").trim();if(text)return text}throw Object.assign(new Error("EMPTY_MODEL_OUTPUT"),{status:502})}
async function call(env,slot,messages,maxTokens,ms,taskId,profile){const endpoint=await dynamicChatEndpoint(env);return fetchGatewayBounded(endpoint,{method:"POST",headers:{"content-type":"application/json",accept:"application/json",...aiGatewayRequestHeaders(env,ms,{expert_slot:slot,task_id:taskId,...profile})},body:JSON.stringify({model:dynamicRouteModel(env),messages,temperature:0.2,stream:false,...(maxTokens?{max_tokens:maxTokens}:{})})},ms)}
async function stage({env,id,slot,stageName,role,userPrompt,systemPrompt,maxTokens,stageTimeoutMs,deadline,profile}){await ensureNotCancelled(env,id);const left=remaining(deadline);if(left<=0)throw Object.assign(new Error("TASK_DEADLINE_EXCEEDED"),{status:504,details:{stage:stageName}});const timeoutMs=Math.max(1,Math.min(stageTimeoutMs,left)),started=Date.now();await save(env,id,{status:"running",current_stage:stageName,current_route_slot:slot,current_task_profile:profile,stage_started_at:now()});try{const out=await call(env,slot,[{role:"system",content:systemPrompt},{role:"user",content:userPrompt}],maxTokens,timeoutMs,id,profile),content=contentOf(out.payload),model=out.route.model,provider=out.route.provider,co=company(model,provider),elapsed_ms=Date.now()-started;if(!allowedRouteSelection(model,provider))throw Object.assign(new Error("DYNAMIC_ROUTE_POLICY_VIOLATION"),{status:502,details:{stage:stageName,slot,model,provider}});if(!co)throw Object.assign(new Error("DYNAMIC_ROUTE_COMPANY_UNVERIFIABLE"),{status:502,details:{stage:stageName,slot,model,provider}});return{slot,model,provider,company:co,content,usage:redact(out.payload?.usage||null),attempts:[{slot,model,provider,company:co,attempt:1,status:"completed",elapsed_ms}]}}catch(e){await save(env,id,{last_stage_error:String(e?.message||e),last_failed_stage:stageName,last_failed_route_slot:slot,last_failed_elapsed_ms:Date.now()-started});throw Object.assign(e,{details:{...(e?.details||{}),stage:stageName,slot}})}}

async function run(req,env){
  if(!aiGatewayConfigured(env))return err("AI_GATEWAY_NOT_CONFIGURED","Cloudflare AI Gateway token, gateway id, route, or account id is not configured",503);
  const rate=await gs(env,"/rate","POST",{limit:int(env.RATE_LIMIT_PER_MIN,20)});if(!rate.ok)return err("RATE_LIMITED","Expert budget exceeded",429);
  const b=await parse(req);if(!b.prompt||typeof b.prompt!=="string")return err("INVALID_REQUEST","prompt required",400);
  const profile=profileExpertTask(b);
  const id=String(b.task_id||b.request_id||rid()),previous=await load(env,id);if(previous.task)return err("DUPLICATE_TASK","task_id already exists; duplicate expert execution blocked",409,{task_id:id,status:previous.task.status});
  const count=Math.max(2,Math.min(MAX_MODELS,int(b.model_count,4))),totalSeconds=clamp(b.timeout_seconds,10,300,240),expertStageSeconds=clamp(b.model_timeout_seconds,1,60,45),judgeStageSeconds=clamp(b.judge_timeout_seconds,1,75,60),deadline=Date.now()+totalSeconds*1000,lock=await acquire(env,id,Math.min(900,Math.max(300,totalSeconds+30)));if(!lock.ok)return err("BUSY","Another expert task is active",409,lock.active);
  const expertSlots=Array.from({length:count-1},(_,i)=>`expert-${i+1}`),judgeSlot="judge";
  await save(env,id,{status:"routing",created_at:now(),requested_model_count:count,dynamic_route:aiGatewayDescriptor(env).route,planned_route_slots:[...expertSlots,judgeSlot],task_profile:profile,total_timeout_seconds:totalSeconds,expert_stage_timeout_seconds:expertStageSeconds,judge_stage_timeout_seconds:judgeStageSeconds,worker_retries:0,route_fallbacks:"cloudflare-managed"});
  try{
    const answers=[],receipt=[];
    for(let i=0;i<expertSlots.length;i++){const slot=expertSlots[i],role=Array.isArray(b.roles)&&b.roles[i]?String(b.roles[i]).slice(0,120):`Expert ${i+1}`,r=await stage({env,id,slot,stageName:slot,role,userPrompt:b.prompt,systemPrompt:`You are ${role}. Analyze independently. Do not use tools or web. State uncertainty and unsupported assumptions.`,maxTokens:int(b.max_tokens,0)||undefined,stageTimeoutMs:expertStageSeconds*1000,deadline,profile});answers.push({slot,model:r.model,provider:r.provider,company:r.company,role,content:r.content,usage:r.usage});receipt.push({stage:slot,role,route_slot:slot,task_profile:profile,final_model:r.model,provider:r.provider,company:r.company,attempts:r.attempts})}
    await ensureNotCancelled(env,id);if(remaining(deadline)<=0)throw Object.assign(new Error("TASK_DEADLINE_EXCEEDED"),{status:504});const synthesis=`Question:\n${b.prompt}\n\nIndependent expert answers:\n${answers.map((a,i)=>`[${i+1}] ${a.model} (${a.role})\n${a.content}`).join("\n\n")}`,jr=await stage({env,id,slot:judgeSlot,stageName:"judge",role:"Final judge",userPrompt:synthesis,systemPrompt:"You are the final judge. Compare the independent analyses, resolve conflicts, reject unsupported claims, and return the best calibrated synthesis. Do not use tools or web.",maxTokens:int(b.max_tokens,0)||undefined,stageTimeoutMs:judgeStageSeconds*1000,deadline,profile});receipt.push({stage:"judge",role:"Final judge",route_slot:judgeSlot,task_profile:profile,final_model:jr.model,provider:jr.provider,company:jr.company,attempts:jr.attempts});
    const participants=[...answers,jr],models=participants.map(x=>x.model),companies=participants.map(x=>x.company),uniqueCompanies=new Set(companies).size;if(models.length!==count||uniqueCompanies!==count)throw Object.assign(new Error("COMPANY_DIVERSITY_INVARIANT_FAILED"),{status:502,details:{models,companies,unique_companies:uniqueCompanies,required:count}});
    const rec={status:"completed",dynamic_route:aiGatewayDescriptor(env).route,task_profile:profile,models,companies,answers,judge:{slot:judgeSlot,model:jr.model,provider:jr.provider,company:jr.company,content:jr.content,usage:jr.usage},execution_receipt:receipt,company_diverse:true,finished_at:now(),elapsed_ms:Math.max(0,totalSeconds*1000-remaining(deadline))},contentDigest=await outputDigest({task_profile:profile,models,companies,answers,judge:rec.judge});await save(env,id,{status:rec.status,dynamic_route:rec.dynamic_route,task_profile:profile,models,companies,answer_count:answers.length,judge_model:jr.model,execution_receipt:receipt,company_diverse:true,finished_at:rec.finished_at,elapsed_ms:rec.elapsed_ms,output_digest:contentDigest,content_storage:"response-only-not-durable",answers:null,judge:null});return json({ok:true,task_id:id,...rec,output_digest:contentDigest,durable_content:false});
  }catch(e){if(e?.message==="CANCELLED"){await save(env,id,{status:"cancelled",finished_at:now()});return err("CANCELLED","Expert task cancelled",409,{task_id:id})}await save(env,id,{status:"failed",error:String(e?.message||"UPSTREAM_UNAVAILABLE"),message:String(e?.message||e),details:redact(e?.details),finished_at:now()});return err(e?.message||"UPSTREAM_UNAVAILABLE","Cloudflare dynamic-route expert execution failed",e?.status||502,{task_id:id,...(e?.details?{stage_details:redact(e.details)}:{})})}finally{await release(env,id)}
}

async function handle(req,env){const u=new URL(req.url);if(req.method==="GET"&&u.pathname==="/health")return json({ok:true,status:"ready",service:SERVICE,api_version:API_VERSION,ai_gateway:aiGatewayDescriptor(env)});if(req.method==="GET"&&(u.pathname==="/v1/policy"||u.pathname==="/policy"))return json({ok:true,service:SERVICE,policy:POLICY});if(req.method==="GET"&&(u.pathname==="/v1/capabilities"||u.pathname==="/capabilities"))return json({ok:true,service:SERVICE,capabilities:CAP,capability_abi_version:CAPABILITY_ABI_VERSION,capability_manifest:expertCapabilityManifest({configured:aiGatewayConfigured(env)})});if(req.method==="GET"&&(u.pathname==="/quota"||u.pathname==="/v1/quota"))return json({ok:true,rate_limit_per_min:int(env.RATE_LIMIT_PER_MIN,20),single_active_task:true,max_models:MAX_MODELS,worker_retries:0,model_fallbacks:"cloudflare-dynamic-route",default_total_timeout_seconds:240,default_expert_stage_timeout_seconds:45,default_judge_stage_timeout_seconds:60});if(req.method==="GET"&&u.pathname==="/source")return json({ok:true,service:SERVICE,api_version:API_VERSION,source_digest:await digest(),secrets_redacted:true});if(req.method==="GET"&&u.pathname==="/v1/acceptance/latest")return json({ok:true,service:SERVICE,status:"not_verified",run_id:null,receipt_digest:null});if(req.method==="GET"&&u.pathname==="/openapi.json")return json({openapi:"3.1.0",info:{title:"Expert Center",version:API_VERSION},paths:{"/health":{get:{}},"/v1/policy":{get:{}},"/v1/capabilities":{get:{}},"/v1/run":{post:{}},"/v1/status":{post:{}},"/v1/cancel":{post:{}}}});if(req.method==="POST"&&u.pathname==="/v1/status"){const b=await parse(req);if(!b.task_id)return err("INVALID_REQUEST","task_id required",400);const x=await load(env,b.task_id);return x.task?json({ok:true,task:x.task}):err("INVALID_REQUEST","Task not found",404)}if(req.method==="POST"&&u.pathname==="/v1/cancel"){const b=await parse(req);if(!b.task_id)return err("INVALID_REQUEST","task_id required",400);const x=await gs(env,`/task/${encodeURIComponent(b.task_id)}/cancel`,"POST",{},`task:${b.task_id}`);return json({ok:x.ok,task:x.task||null,cancellation_pending:true,lock_retained:true},202)}if(req.method==="POST"&&u.pathname==="/v1/run")return run(req,env);return err("INVALID_REQUEST","Route not found",404)}
export default{async fetch(req,env){try{return await handle(req,env)}catch(e){return err(e?.message||"INTERNAL_ERROR","Request failed",e?.status||500,e?.details)}}};
