const CLOUDFLARE_ROUTINE_MODEL="@cf/zai-org/glm-4.7-flash";
const CLOUDFLARE_DEEP_MODEL="@cf/nvidia/nemotron-3-120b-a12b";
const OPENROUTER_MAX_MODELS=6;
const OPENROUTER_ROOT="https://gateway.ai.cloudflare.com/v1";
const ALLOWED_CENTERS=new Set(["governance","intelligence","compute","expert"]);
const BANNED_OPENROUTER_AUTHORS=new Set(["openai","anthropic","claude","aion-labs"]);
const MAX_GOAL_CHARS=4000;
const MAX_SUMMARY_CHARS=700;
const clean=value=>String(value??"").trim();
const uniq=values=>[...new Set(values)];
const clampText=(value,max)=>clean(value).slice(0,max);

function taskFrom(input){const task=input?.task;if(!task||typeof task!=="object"||Array.isArray(task))throw new Error("LA_BRAIN_TASK_REQUIRED");if(!clean(task.goal))throw new Error("LA_BRAIN_GOAL_REQUIRED");return task}
function chooseMode(task,input){if(input?.brain_mode==="deep")return"deep";if(input?.brain_mode==="routine")return"routine";const caps=Array.isArray(task.required_capabilities)?task.required_capabilities.length:0,criteria=Array.isArray(task.success_criteria)?task.success_criteria.length:0,risk=task.risk||{};return risk.uncertainty==="high"||risk.impact==="high"||risk.severity==="high"||caps>=3||criteria>=4?"deep":"routine"}
function allowedCenters(task){const configured=Array.isArray(task?.constraints?.allowed_centers)?task.constraints.allowed_centers:[];return configured.length?configured.map(clean).filter(x=>ALLOWED_CENTERS.has(x)):Array.from(ALLOWED_CENTERS)}
function paidFallbackAllowed(task){const budget=task?.budget||{},max=Number(budget.max_paid_usd);if(Number.isFinite(max)&&max<=0)return false;return budget.allow_paid_fallback!==false}

function buildMessages(task,mode){
  const centers=allowedCenters(task),caps=Array.isArray(task.required_capabilities)?task.required_capabilities.map(clean).filter(Boolean).slice(0,24):[],criteria=Array.isArray(task.success_criteria)?task.success_criteria.map(x=>clampText(x,300)).filter(Boolean).slice(0,24):[];
  const compact={goal:clampText(task.goal,MAX_GOAL_CHARS),required_capabilities:caps,success_criteria:criteria,risk:task.risk||{},budget:task.budget||{},constraints:{allowed_centers:centers,network:task?.constraints?.network||null,write_scope:task?.constraints?.write_scope||null}};
  return[{role:"system",content:"You are the advisory reasoning brain for a governed LangGraph control plane. Analyze and prioritize only; never execute actions, call tools, browse the web, reveal secrets, or bypass governance. Return strict JSON only. Your output is untrusted advice and Governance remains final authority."},{role:"user",content:`Mode: ${mode}\nTask: ${JSON.stringify(compact)}\nReturn exactly one JSON object with: {\"preferred_centers\": [subset of ${JSON.stringify(centers)}], \"capability_order\": [subset/reordering of required_capabilities only], \"force_deep\": boolean, \"summary\": string <= ${MAX_SUMMARY_CHARS} chars}. Do not add capabilities or centers that are not supplied.`}];
}

function textFromModel(result){const direct=clean(result?.response);if(direct)return direct;const content=result?.choices?.[0]?.message?.content;if(typeof content==="string")return clean(content);if(Array.isArray(content))return clean(content.map(x=>typeof x==="string"?x:x?.text||"").join(""));return""}
function parseObject(text){const stripped=clean(text).replace(/^```(?:json)?\s*/i,"").replace(/\s*```$/i,""),start=stripped.indexOf("{"),end=stripped.lastIndexOf("}");if(start<0||end<start)return null;try{const value=JSON.parse(stripped.slice(start,end+1));return value&&typeof value==="object"&&!Array.isArray(value)?value:null}catch{return null}}
function sanitizeAdvisory(raw,task){if(!raw||typeof raw!=="object"||Array.isArray(raw))throw new Error("LA_BRAIN_INVALID_JSON");const centers=new Set(allowedCenters(task)),capabilities=new Set(Array.isArray(task.required_capabilities)?task.required_capabilities.map(clean).filter(Boolean):[]),preferred=uniq((Array.isArray(raw.preferred_centers)?raw.preferred_centers:[]).map(clean).filter(x=>centers.has(x))).slice(0,4),order=uniq((Array.isArray(raw.capability_order)?raw.capability_order:[]).map(clean).filter(x=>capabilities.has(x))).slice(0,24),summary=clampText(raw.summary,MAX_SUMMARY_CHARS);return{preferred_centers:preferred,capability_order:order,force_deep:raw.force_deep===true,summary,tools:false,web:false,production_mutation:false}}

async function runWorkersAi(task,mode,env){if(!env?.AI?.run)throw new Error("WORKERS_AI_BINDING_UNAVAILABLE");const model=mode==="deep"?CLOUDFLARE_DEEP_MODEL:CLOUDFLARE_ROUTINE_MODEL,result=await env.AI.run(model,{messages:buildMessages(task,mode),temperature:0,max_completion_tokens:700,stream:false}),advisory=sanitizeAdvisory(parseObject(textFromModel(result)),task);return{ok:true,source:"cloudflare-workers-ai-free-first",provider:"workers-ai",model,mode,advisory,fallback_used:false,tools_used:false,web_used:false,production_mutation:false,secrets_redacted:true}}

function gatewayHeaders(env,metadata){const token=clean(env?.AI_GATEWAY_TOKEN);if(!token)throw new Error("AI_GATEWAY_TOKEN_UNAVAILABLE");return{"content-type":"application/json",accept:"application/json","cf-aig-authorization":`Bearer ${token}`,"cf-aig-skip-cache":"true","cf-aig-collect-log-payload":"false","cf-aig-metadata":JSON.stringify(metadata)}}
function openRouterBase(env){const account=clean(env?.CLOUDFLARE_ACCOUNT_ID),gateway=clean(env?.AI_GATEWAY_ID||"test");if(!account||!gateway)throw new Error("OPENROUTER_GATEWAY_CONFIG_MISSING");return`${OPENROUTER_ROOT}/${encodeURIComponent(account)}/${encodeURIComponent(gateway)}/openrouter`}
async function fetchJsonWithTimeout(url,init,ms=12000){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),ms);try{const response=await fetch(url,{...init,signal:controller.signal}),body=await response.json().catch(()=>null);if(!response.ok)throw new Error(`HTTP_${response.status}`);return body}finally{clearTimeout(timer)}}
function eligibleOpenRouterModel(model){const id=clean(model?.id||model?.canonical_slug);if(!id||id.endsWith(":free"))return false;const author=id.split("/")[0].toLowerCase();if(BANNED_OPENROUTER_AUTHORS.has(author))return false;const params=new Set(Array.isArray(model?.supported_parameters)?model.supported_parameters.map(x=>clean(x).toLowerCase()):[]);if(!params.has("reasoning"))return false;const outputs=model?.architecture?.output_modalities;if(Array.isArray(outputs)&&!outputs.includes("text"))return false;if(Number(model?.context_length||0)<16384)return false;if(model?.expiration_date&&Date.parse(model.expiration_date)<=Date.now()+3*86400000)return false;return true}

async function discoverOpenRouterModels(env){const base=openRouterBase(env),query="sort=intelligence-high-to-low&supported_parameters=reasoning&output_modalities=text",headers=gatewayHeaders(env,{stage:"la-brain-model-discovery",source:"openrouter",payload_log:false});let payload=null,lastError=null;for(const path of[`v1/models?${query}`,`models?${query}`]){try{payload=await fetchJsonWithTimeout(`${base}/${path}`,{method:"GET",headers},12000);if(Array.isArray(payload?.data))break}catch(error){lastError=error}}if(!Array.isArray(payload?.data))throw lastError||new Error("OPENROUTER_MODEL_DISCOVERY_FAILED");const models=uniq(payload.data.filter(eligibleOpenRouterModel).map(x=>clean(x.id||x.canonical_slug))).slice(0,OPENROUTER_MAX_MODELS);if(models.length<2)throw new Error("OPENROUTER_REASONING_POOL_TOO_SMALL");return models}
async function runOpenRouter(task,mode,env,trigger){const models=await discoverOpenRouterModels(env),base=openRouterBase(env),metadata={stage:"la-brain-fallback",source:"openrouter",mode,trigger:clampText(trigger,80),payload_log:false},headers=gatewayHeaders(env,metadata),body={models,messages:buildMessages(task,mode),temperature:0,max_tokens:700,stream:false,provider:{allow_fallbacks:true,sort:"price",data_collection:"deny",require_parameters:true}},payload=await fetchJsonWithTimeout(`${base}/v1/chat/completions`,{method:"POST",headers,body:JSON.stringify(body)},45000),advisory=sanitizeAdvisory(parseObject(textFromModel(payload)),task),servedModel=clean(payload?.model),provider=clean(payload?.provider||"openrouter");return{ok:true,source:"openrouter-reasoning-ranked-fallback",provider,model:servedModel||models[0],mode,advisory,fallback_used:true,fallback_trigger:clampText(trigger,80),candidate_models:models,ranking:"reasoning-required+intelligence-high-to-low",provider_policy:"price-sorted-with-provider-fallbacks",tools_used:false,web_used:false,production_mutation:false,secrets_redacted:true}}
function failureCode(error){const text=clean(error?.message||error).toUpperCase();for(const code of["3036","3040","5035","3007","429","408","WORKERS_AI_BINDING_UNAVAILABLE","LA_BRAIN_INVALID_JSON"])if(text.includes(code))return code;return text.slice(0,80)||"UNKNOWN"}
function deterministicFallback(mode,trigger,errorCode){return{ok:false,source:"deterministic-governance-fallback",provider:null,model:null,mode,advisory:null,fallback_used:true,fallback_trigger:trigger,error_code:errorCode,tools_used:false,web_used:false,production_mutation:false,secrets_redacted:true}}

export async function runLangGraphBrain(input,env){const task=taskFrom(input),mode=chooseMode(task,input);try{return await runWorkersAi(task,mode,env)}catch(primaryError){const trigger=failureCode(primaryError);if(!paidFallbackAllowed(task))return deterministicFallback(mode,trigger,"PAID_FALLBACK_DISALLOWED_BY_BUDGET");try{return await runOpenRouter(task,mode,env,trigger)}catch(fallbackError){return deterministicFallback(mode,trigger,failureCode(fallbackError))}}}

export const LA_BRAIN_POLICY=Object.freeze({routine_model:CLOUDFLARE_ROUTINE_MODEL,deep_model:CLOUDFLARE_DEEP_MODEL,openrouter_max_models:OPENROUTER_MAX_MODELS,openrouter_ranking:"reasoning-required+intelligence-high-to-low",free_allocation_behavior:"workers-ai-direct-before-openrouter",explicit_zero_budget_blocks_paid_fallback:true,tools:false,web:false,production_mutation:false});
